### ISSUE TITLE
导航栏显示错误.

### ISSUE THREAD

**Issue by fengguowudi** [xnuc/cnblogs-theme-blogure#93]
![image](https://user-images.githubusercontent.com/55879152/209595578-3626ed57-c5b3-4986-8aee-c5981598a496.png)

**Comment by hookcat** [comment]
饶 是不是博客园更新了

**Comment by eitfit** [comment]
果哥 贴下配置

**Comment by eitfit** [comment]
复现了

![image](https://user-images.githubusercontent.com/64666574/212837965-069ca679-5fa9-4351-a136-b40b305a90ea.png)

原因 博客园多了一些空的列表导致(ps 不知道之前一直是这样还是后面有改动才这样)

**Comment by eitfit** [comment]
> 怎么解决·？

按照文档重新配置下就可以了

**Comment by eitfit** [comment]
> 那其他按钮呢？就你把空白删了？

博客园设置自己选择需要哪些按钮呀 这个主题0配置
